# Generated by Django 3.0.3 on 2020-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_comment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='use string', max_length=255),
            preserve_default=False,
        ),
    ]
