# Generated by Django 3.0.3 on 2020-02-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200224_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
