# Generated by Django 3.0.3 on 2020-02-24 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_auto_20200224_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='users',
            new_name='usernames',
        ),
        migrations.RemoveField(
            model_name='group_name',
            name='owner',
        ),
        migrations.AddField(
            model_name='group_name',
            name='usermanes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
