# Generated by Django 3.0.3 on 2020-02-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20200224_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_name',
            old_name='usernames',
            new_name='name',
        ),
    ]
