# Generated by Django 3.0.3 on 2020-02-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20200224_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='usernames',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='group_name',
            old_name='name',
            new_name='owner',
        ),
    ]
