# Generated by Django 3.0.3 on 2020-02-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20200224_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_Name',
            new_name='User',
        ),
    ]
