# Generated by Django 3.0.3 on 2020-02-24 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20200224_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
