# Generated by Django 3.0.3 on 2020-02-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='comments',
            field=models.ManyToManyField(related_name='chatroom', to='chat.Comment'),
        ),
    ]
