# Generated by Django 3.0.3 on 2020-02-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20200224_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='new',
            field=models.TextField(default=''),
        ),
    ]
