# Generated by Django 3.0.3 on 2020-02-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_auto_20200224_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='new',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
