# Generated by Django 3.0.3 on 2020-02-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20200224_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='comments',
            field=models.ManyToManyField(related_name='chatroom', to='chat.Comment'),
        ),
    ]
