# Generated by Django 3.0.3 on 2020-02-25 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0023_chatroom_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='comments',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='chat',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='chat.Chatroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
