# Generated by Django 3.0.3 on 2020-02-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_auto_20200226_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
